name: Allyn Edmonds
favicon: null
layout_spectrum: 0.25346
typography_spectrum: 0.50083
title: 'My life as a father, photography and ride-share driver.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cbccce'
    - '#1a1a1a'
    - '#9f9a96'
    - '#51595c'
    - '#ab4349'
  brandStrength: 0.5
  lightness: 0.12974455137737095
  saturation: 0.6875
  rhythmicContrast: 0.35833680955693126
purpose: []
