name: Allyn Edmonds
favicon: null
layout_spectrum: 0.49527
typography_spectrum: 0.50083
title: 'My life as a father, photography and ride-share driver.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7f8395'
    - '#d3e5eb'
    - '#c0ccd4'
    - '#262128'
    - '#6e4b4d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
